export const FETCHING_REQUEST = 'FETCHING_REQUEST';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_FAILURE = 'FETCHING_FAILURE';
export const HANDLING_INPUT = 'HANDLING_INPUT';
export const UPDATING_FAVS = 'UPDATING_FAVS';